name: CI-CD Backend
on:
  push:
    branches: [main]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout
      #   uses: actions/checkout@v2

      # - name: Login Docker Hub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      # - name: Setup Docker Buildx
      #   uses: docker/setup-buildx-action@v1
      #   id: buildx

      # - name: Build and Push Docker Image
      #   uses: docker/build-push-action@v2
      #   id: docker_build
      #   with:
      #     context: ./
      #     file: ./Dockerfile
      #     builder: ${{ steps.buildx.outputs.name }}
      #     push: true
      #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/flask-helloworld

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          sync: true
          script: |
            cd build/  
            ls
            cd Backend_api/
            ls
            git pull origin main
            cd ..
            docker compose up --build -d backend-api
