name: CI-CD Backend Deploy
on:
  push:
    branches: [main]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

#       - name: Login Docker Hub
#         uses: docker/login-action@v1
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      # - name: Setup Docker Buildx
      #   uses: docker/setup-buildx-action@v1
      #   id: buildx

      # - name: Build and Push Docker Image
      #   uses: docker/build-push-action@v2
      #   id: docker_build
      #   with:
      #     context: ./
      #     file: ./Dockerfile
      #     builder: ${{ steps.buildx.outputs.name }}
      #     push: true
      #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/flask-helloworld

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          sync: true
          script: |
            cd build/  
            cd Backend_api/
            git remote set-url origin https://cin12211:${{ secrets.GIT_TOKEN }}@github.com/Finder-Application/Backend_api.git
            git pull origin
            cd ..
            ls
            docker ps
            docker compose up --build backend-api -d
